const fs=require('fs');const {JSDOM}=require('jsdom');
const pf=JSON.parse(fs.readFileSync('data/plano-trf3-tecnico.json','utf8'));
const ef=JSON.parse(fs.readFileSync('data/edital-trf3-tjaa-2024.json','utf8'));
const pid='pln';
const ed={id:'e1',criadoEm:'2026-06-12',titulo:'TRF3 Tecnico 2026',banca:'FCC',orgao:'TRF3',cargo:'Tec',estado:'SP',notaCorte:84,arquivado:false,foto:'',disciplinas:pf.disciplinas};
const ed2={id:'e2',criadoEm:'2026-06-12',titulo:'TJ-RJ Tecnico 2026',banca:'FGV',orgao:'TJ-RJ',estado:'RJ',notaCorte:68,arquivado:false,foto:'',disciplinas:ef.disciplinas};
const state={versao:2,planos:[{id:pid,criadoEm:'2026-06-12',plano:Object.assign({},pf.plano,{ritmoAtivo:'sustentavel',gerado_em:'2026-06-08',combinado:{fontes:['A','B'],pct:50,nivel:'alta',mensagem:'ok'}}),disciplinas:pf.disciplinas,cronogramas:pf.cronogramas||{sustentavel:[],hardcore:[]},links:[]}],planoAtivoId:pid,sessoes:[],revisoes:[],simulados:[],agenda:[],editais:[ed,ed2],config:{rotinaEstudos:null,tema:'claro',criadoEm:'2026-06-12',atualizadoEm:'2026-06-12',googleCalendar:{calendarId:'primary',eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.confirm=()=>false;window.fetch=()=>Promise.reject(new Error('no net'));
window.FirebaseSync={status(){return{estado:'sincronizado',texto:'ok',fonte:'Firebase',usuario:{email:'casar70@gmail.com',uid:'u1'}};},iniciar(){},agendarEnvio(){},sincronizarAgora(){return Promise.resolve();},login(){return Promise.resolve();},logout(){return Promise.resolve();},ativo(){return true;},carregarCatalogoGlobal(){return Promise.resolve([]);}};
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
const errs=[];window.addEventListener('error',e=>errs.push(e.error&&e.error.stack||e.message));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.dispatchEvent(new window.Event('firebase-sync-ready'));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
errs.length=0;window.location.hash='#planos';window.dispatchEvent(new window.Event('hashchange'));
console.log('planos', errs.length?('ERR '+errs[0]):'ok');
console.log('comparar secao:', !!main.querySelector('#cmp-secao'));
console.log('selA opts:', main.querySelectorAll('#cmp-a option').length, 'selB opts:', main.querySelectorAll('#cmp-b option').length);
console.log('resultado preenchido:', (main.querySelector('#cmp-sec-resultado')||{}).innerHTML ? 'sim' : 'nao');
console.log('verdict present:', !!main.querySelector('.conciliar-veredito'));
// change B to same as A
const a=main.querySelector('#cmp-a'),b=main.querySelector('#cmp-b');
b.value=a.value; b.dispatchEvent(new window.Event('change'));
console.log('same-edital hint:', main.querySelector('#cmp-sec-resultado').innerHTML.indexOf('diferentes')>=0);
errs.length=0;
console.log('errors after change:', errs.length?errs[0]:'none');
// edital tab no banner
window.location.hash='#edital';window.dispatchEvent(new window.Event('hashchange'));
console.log('edital banner gone:', !main.querySelector('.compat-editais'), errs.length?('ERR '+errs[0]):'ok');
