const fs=require('fs');const {JSDOM}=require('jsdom');
const pf=JSON.parse(fs.readFileSync('data/plano-trf3-tecnico.json','utf8'));
const pid='pln';
const state={versao:2,planos:[{id:pid,criadoEm:'2026-06-12',plano:Object.assign({},pf.plano,{ritmoAtivo:'sustentavel',gerado_em:'2026-06-08'}),disciplinas:pf.disciplinas,cronogramas:pf.cronogramas||{sustentavel:[],hardcore:[]},links:[]}],planoAtivoId:pid,sessoes:[{id:'s1',planoId:pid,data:'2026-06-13',tipo:'teoria',duracaoMin:120,qFeitas:60,qCertas:45}],revisoes:[],simulados:[],agenda:[],editais:[],config:{tema:'escuro',criadoEm:'2026-06-12',atualizadoEm:'2026-06-12',googleCalendar:{calendarId:'primary',eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.confirm=()=>false;window.fetch=()=>Promise.reject(new Error('no net'));
window.FirebaseSync={status(){return{estado:'sincronizado',texto:'ok',fonte:'Firebase',usuario:{email:'casar70@gmail.com',uid:'u1'}};},iniciar(){},agendarEnvio(){},sincronizarAgora(){return Promise.resolve();},login(){return Promise.resolve();},logout(){return Promise.resolve();},ativo(){return true;},carregarCatalogoGlobal(){return Promise.resolve([]);}};
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
const errs=[];window.addEventListener('error',e=>errs.push(e.error&&e.error.stack||e.message));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.dispatchEvent(new window.Event('firebase-sync-ready'));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
window.location.hash='#hoje';window.dispatchEvent(new window.Event('hashchange'));
const total=main.querySelectorAll('.painel-disc-mobile').length;
const extras=main.querySelectorAll('.painel-disc-extra').length;
const btn=main.querySelector('[data-painel-vermais]');
console.log('total discs:', total, 'extras:', extras);
console.log('btn text initial:', btn && btn.textContent.trim(), 'aria:', btn && btn.getAttribute('aria-expanded'));
// click expand
btn.click();
const btn2=main.querySelector('[data-painel-vermais]');
const exp=main.querySelector('.painel-disciplinas-mobile.expandido');
console.log('after click — expandido class:', !!exp, 'btn text:', btn2 && btn2.textContent.trim(), 'aria:', btn2 && btn2.getAttribute('aria-expanded'));
// click again -> collapse
btn2.click();
const btn3=main.querySelector('[data-painel-vermais]');
const exp2=main.querySelector('.painel-disciplinas-mobile.expandido');
console.log('after click 2 — expandido:', !!exp2, 'btn text:', btn3 && btn3.textContent.trim());
console.log('errors:', errs.length?errs[0]:'none');
