const fs=require('fs');const {JSDOM}=require('jsdom');
const pf=JSON.parse(fs.readFileSync('data/plano-trf3-tecnico.json','utf8'));
const ef=JSON.parse(fs.readFileSync('data/edital-trf3-tjaa-2024.json','utf8'));
const pid='pln';
const state={versao:2,planos:[{id:pid,criadoEm:'2026-06-12',plano:Object.assign({},pf.plano,{ritmoAtivo:'sustentavel'}),disciplinas:pf.disciplinas,cronogramas:{sustentavel:[],hardcore:[]},links:[]}],planoAtivoId:pid,sessoes:[],revisoes:[],simulados:[],agenda:[],editais:[Object.assign({id:'e1',criadoEm:'2026-06-12',titulo:ef.titulo,banca:ef.banca,cargo:ef.cargo,orgao:'TRF3',estado:'SP',notaCorte:84,arquivado:false,foto:'',disciplinas:ef.disciplinas})],config:{metaQuestoesSemana:120,tema:'claro',criadoEm:'2026-06-12',atualizadoEm:'2026-06-12',nomeUsuario:'Samuel',googleCalendar:{clientId:'',calendarId:'primary',eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=window.matchMedia||function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.confirm=()=>false;window.fetch=()=>Promise.reject(new Error('no net'));
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
const errs=[];window.addEventListener('error',e=>errs.push(e.error&&e.error.stack||e.message));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
['planos','ajustes'].forEach(r=>{errs.length=0;window.location.hash='#'+r;window.dispatchEvent(new window.Event('hashchange'));console.log(r.padEnd(10),'len',main.innerHTML.length, errs.length?('ERR '+errs[0]):'ok');});
window.location.hash='#ajustes';window.dispatchEvent(new window.Event('hashchange'));
console.log('admin tem "Planos cadastrados":', main.innerHTML.indexOf('Planos cadastrados')>=0);
console.log('admin tem busca #adm-busca:', !!main.querySelector('#adm-busca'));
console.log('admin card tem catalogo-foto:', !!main.querySelector('.plano-mini-top-foto .catalogo-foto'));
// abrir editor "Novo edital" e verificar campo de foto
errs.length=0;
const novo=main.querySelector('#adm-novo'); novo.click();
const modal=window.document.getElementById('modal-raiz');
console.log('editor abriu com #ee-foto:', !!modal.querySelector('#ee-foto'), errs.length?('ERR '+errs[0]):'ok');
// editar edital existente -> foto field present + preview placeholder
errs.length=0;
window.document.getElementById('modal-raiz').innerHTML='';
window.location.hash='#ajustes';window.dispatchEvent(new window.Event('hashchange'));
const editar=main.querySelector('[data-ed-editar]'); editar.click();
console.log('editar abriu com #ee-foto:', !!window.document.getElementById('modal-raiz').querySelector('#ee-foto'), errs.length?('ERR '+errs[0]):'ok');
