const fs=require('fs');const {JSDOM}=require('jsdom');
const planoFile=JSON.parse(fs.readFileSync('data/plano-trf3-tecnico.json','utf8'));
const pid='pln';
const state={versao:2,planos:[{id:pid,criadoEm:'2026-06-12',plano:Object.assign({},planoFile.plano),disciplinas:planoFile.disciplinas,cronogramas:{sustentavel:[],hardcore:[]},links:[]}],planoAtivoId:pid,sessoes:[],revisoes:[],simulados:[],agenda:[],editais:[],config:{metaQuestoesSemana:100,tema:'claro',criadoEm:'2026-06-12',atualizadoEm:'2026-06-12',nomeUsuario:'Samuel',googleCalendar:{clientId:'',calendarId:'primary',eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=window.matchMedia||function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.confirm=()=>false;window.fetch=()=>Promise.reject(new Error('no net'));
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
const errs=[];window.addEventListener('error',e=>errs.push(e.error&&e.error.message||e.message));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
window.location.hash='#timer';window.dispatchEvent(new window.Event('hashchange'));
const h=main.innerHTML;
console.log('timer len:',h.length, errs.length?('ERR '+errs[0]):'no errors');
console.log('has play triangle path:', h.indexOf('M132 106')>=0);
console.log('tick lines count:', (h.match(/<line /g)||[]).length);
console.log('has Opcional text:', h.indexOf('Opcional')>=0);
console.log('disc select present:', h.indexOf('timer-disc-select')>=0);
