process.on('uncaughtException',e=>{console.log('UNCAUGHT',e&&e.message);});
const fs=require('fs');const {JSDOM}=require('jsdom');
const ef=JSON.parse(fs.readFileSync('data/edital-trf3-tjaa-2024.json','utf8'));
const ed=Object.assign({id:'e1',criadoEm:'2026-06-12',titulo:ef.titulo,banca:ef.banca,cargo:ef.cargo,orgao:'TRF3',estado:'SP',notaCorte:84,arquivado:false,foto:'',janelaProva:{inicio:'2027-01',fim:'2027-06'},disciplinas:ef.disciplinas});
const state={versao:2,planos:[],planoAtivoId:null,sessoes:[],revisoes:[],simulados:[],agenda:[],editais:[ed],config:{tema:'claro',criadoEm:'2026-06-12',rotinaEstudos:{minBloco:45,maxBloco:60,dias:{dom:{ativo:true,minutos:180},seg:{ativo:true,minutos:210},ter:{ativo:true,minutos:180},qua:{ativo:true,minutos:210},qui:{ativo:true,minutos:240},sex:{ativo:true,minutos:300},sab:{ativo:true,minutos:300}}},googleCalendar:{eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=window.matchMedia||function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.fetch=()=>Promise.reject(new Error('x'));window.history.pushState=function(){};
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
window.location.hash='#planos';window.dispatchEvent(new window.Event('hashchange'));
main.querySelector('[data-pl-iniciar]').click();
const modal=window.document.getElementById('modal-raiz');
modal.querySelector('#gp-proximo').click();modal.querySelector('#gp-proximo').click();modal.querySelector('#gp-proximo').click();
modal.querySelector('#form-gerar-plano-rotina').dispatchEvent(new window.Event('submit',{cancelable:true,bubbles:true}));
const st=JSON.parse(window.localStorage.getItem('estudos.v1'));
const ativo=st.planos.find(p=>p.id===st.planoAtivoId);
const cron=ativo.cronogramas[ativo.plano.ritmoAtivo];
function add(iso,n){const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10);}
const linhas=cron.map(sem=>{const ini=sem.inicio,fim=add(ini,7);const tot=st.agenda.filter(a=>a.data>=ini&&a.data<fim).reduce((n,x)=>n+x.duracaoMin,0);return 's'+sem.semana+'='+(tot/60)+'h';});
fs.writeFileSync('/tmp/wk.txt', linhas.join(' ')+'\n');
console.log('WROTE', linhas.length, 'weeks');
