const fs=require('fs');const {JSDOM}=require('jsdom');
const pf=JSON.parse(fs.readFileSync('data/plano-trf3-tecnico.json','utf8'));
const plano=Object.assign({},pf.plano,{ritmoAtivo:'sustentavel',radar:{janela_prova:['2027-01','2027-06']},ritmos:{sustentavel:{meses:6,semanas:26,h_semana:27}}});
const state={versao:2,planos:[{id:'pln',criadoEm:'2026-06-12',plano:plano,disciplinas:pf.disciplinas,cronogramas:{sustentavel:[],hardcore:[]},links:[]}],planoAtivoId:'pln',sessoes:[],revisoes:[],simulados:[],agenda:[],editais:[],config:{tema:'escuro',criadoEm:'2026-06-12',googleCalendar:{eventos:{}}}};
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://example.com/'});
const {window}=dom;global.window=window;
window.Chart=function(){return{destroy(){},update(){}};};window.matchMedia=window.matchMedia||function(){return{matches:false,addEventListener(){},addListener(){}};};
window.scrollTo=function(){};window.fetch=()=>Promise.reject(new Error('no net'));
window.localStorage.setItem('estudos.v1',JSON.stringify(state));
const errs=[];window.addEventListener('error',e=>errs.push(e.error&&e.error.stack||e.message));
['js/frases.js','js/domain.js','js/store.js','js/sync.js','js/timer.js','js/charts.js','js/app.js'].forEach(f=>window.eval(fs.readFileSync(f,'utf8')));
window.document.dispatchEvent(new window.Event('DOMContentLoaded',{bubbles:true}));window.dispatchEvent(new window.Event('load'));
const main=window.document.getElementById('conteudo');
errs.length=0;
window.location.hash='#disciplina-'+pf.disciplinas[0].id;window.dispatchEvent(new window.Event('hashchange'));
console.log('DETALHE len', main.innerHTML.length, errs.length?('ERR '+errs[0]):'ok');
console.log(' voltar flutuante:', !!main.querySelector('.det-voltar-flutuante'));
console.log(' det-add dentro do card hist:', !!main.querySelector('.card-cab-acao #det-add'));
console.log(' subtitulo explicativo removido:', main.innerHTML.indexOf('Edital verticalizado da disciplina')<0);
console.log(' h1 disciplina presente:', /<h1>/.test(main.innerHTML));
// click voltar
main.querySelector('#det-voltar').click();
console.log(' voltar -> hash:', window.location.hash);
